# Generated by Django 5.2 on 2025-04-30 13:45

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_is_superuser_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, help_text='60*60', null=True, upload_to=account.models.profile_directory_path, verbose_name='پروفایل'),
        ),
    ]
