# Generated by Django 5.2 on 2025-05-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_profile'),
        ('shop', '0004_alter_product_price_alter_product_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='compare_list',
            field=models.ManyToManyField(related_name='users_compare_list', to='shop.product', verbose_name='لیست مقایسه'),
        ),
    ]
