# Generated by Django 5.2 on 2025-05-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_compare_list'),
        ('shop', '0010_remove_comment_disliked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='compare_list',
            field=models.ManyToManyField(blank=True, related_name='users_compare_list', to='shop.product', verbose_name='لیست مقایسه'),
        ),
    ]
