# Generated by Django 5.2 on 2025-05-29 10:05

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='Profiles/default-3.webp', help_text='60*60', upload_to=account.models.profile_directory_path, verbose_name='پروفایل'),
        ),
    ]
