# Generated by Django 5.2 on 2025-05-29 11:06

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='Profiles/default-2۰۹۴۵۸۷۳۸۵۳۴.webp', help_text='60*60', upload_to=account.models.profile_directory_path, verbose_name='پروفایل'),
        ),
    ]
