# Generated by Django 5.2 on 2025-05-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_category_slug_alter_post_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_content',
            field=models.TextField(blank=True, help_text='پیش نمایش متن | حداکثر ۳۲۰ کاراکتر', max_length=320, verbose_name='توضیحات کوتاه'),
        ),
    ]
