# Generated by Django 5.2 on 2025-05-08 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_access', models.BooleanField(default=True, help_text='دسترسی همه کاربران از سایت قطع می شود.', verbose_name='دسترسی به سایت')),
                ('post_fee', models.PositiveIntegerField(default=10, help_text='به تومان', validators=[django.core.validators.MinValueValidator(10)], verbose_name='کرایه پست')),
                ('tax_fee', models.PositiveIntegerField(default=10, help_text='به تومان', validators=[django.core.validators.MinValueValidator(10)], verbose_name='مالیات')),
                ('show_offer', models.BooleanField(default=False, verbose_name='نمایش پیشنهاد')),
                ('title', models.CharField(max_length=30, verbose_name='تیتر')),
                ('event', models.CharField(blank=True, max_length=100, verbose_name='مناسبت/علت تخفیف')),
                ('products', models.CharField(blank=True, help_text='بر اساس لیست پیشنهاد های مجاز', max_length=50, verbose_name='محصولات انتخاب شده')),
                ('banner', models.ImageField(upload_to='offers/', verbose_name='بنر')),
                ('alt', models.CharField(help_text='برای سئو', verbose_name='تیتر')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
