# Generated by Django 5.2 on 2025-05-08 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='alt',
        ),
        migrations.AlterField(
            model_name='setting',
            name='banner',
            field=models.ImageField(blank=True, upload_to='offers/', verbose_name='بنر'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='event',
            field=models.CharField(blank=True, max_length=100, verbose_name='(مناسبت/علت تخفیف) پیشنهاد'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='tax_fee',
            field=models.PositiveIntegerField(default=1, help_text='به درصد', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='مالیات'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(blank=True, max_length=30, verbose_name='تیتر پیشنهاد'),
        ),
    ]
