# Generated by Django 5.2 on 2025-05-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_setting_alt_alter_setting_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='تیتر پیشنهاد'),
        ),
    ]
