# Generated by Django 5.2 on 2025-05-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_setting_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='products',
            field=models.CharField(blank=True, help_text='بر اساس لیست پیشنهاد های مجاز', verbose_name='محصولات انتخاب شده'),
        ),
    ]
