# Generated by Django 5.2 on 2025-05-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_setting_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='order_waiting_days',
            field=models.PositiveIntegerField(default=3, help_text='تعداد روز های مورد نیاز برای پردازش هر سفارش', verbose_name='زودترین زمان ثبت سفارش'),
        ),
    ]
