# Generated by Django 5.2 on 2025-05-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_setting_order_waiting_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='orders_per_day',
            field=models.PositiveIntegerField(default=1, verbose_name='بیشترین تعداد سفارش در یک روز'),
        ),
    ]
