# Generated by Django 5.2 on 2025-05-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_setting_orders_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='order_days_limit',
            field=models.PositiveIntegerField(default=3, verbose_name='تعداد روز های قابل انتخاب برای دریافت سفارش'),
        ),
    ]
