# Generated by Django 5.2 on 2025-05-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_setting_order_days_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'باشگاه مشتریان',
                'verbose_name_plural': 'باشگاه مشتریان',
            },
        ),
    ]
