# Generated by Django 5.2 on 2025-05-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='ایمیل'),
        ),
    ]
