# Generated by Django 5.2 on 2025-05-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='footer_text',
            field=models.TextField(blank=True, verbose_name='متن فوتر'),
        ),
        migrations.AddField(
            model_name='setting',
            name='video_text',
            field=models.CharField(blank=True, max_length=150, verbose_name='متن ویدیو'),
        ),
    ]
