# Generated by Django 5.2 on 2025-05-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_aboutus_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.EmailField(max_length=255, unique=True, verbose_name='متن درخواست')),
            ],
            options={
                'verbose_name': 'درخواست عطر',
                'verbose_name_plural': 'درخواست عطر',
            },
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
