# Generated by Django 5.2 on 2025-06-05 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_perfumerequest_delete_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='post_fee_max',
            field=models.PositiveIntegerField(default=1000000, help_text='در صورتی که هزینه سفارش بیشتر از جداکثر بشه کرایه پست رایگان در نظر گرفته میشه', validators=[django.core.validators.MinValueValidator(10)], verbose_name='حداکثر هزینه اعمال پست'),
        ),
    ]
