# Generated by Django 5.2 on 2025-05-02 13:44

import django.core.validators
import django.db.models.deletion
import shop.models
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('WINTER', 'زمستانی'), ('SUMMER', 'تابستانی')], max_length=8, verbose_name='فصل')),
                ('taste', models.CharField(choices=[('SPICY', 'تند'), ('SWEET', 'شیرین'), ('BITTER', 'تلخ'), ('SOUR', 'ترش')], max_length=6, verbose_name='طعم')),
                ('nature', models.CharField(choices=[('WARM', 'گرم'), ('COLD', 'سرد')], max_length=4, verbose_name='طبع')),
                ('gender', models.CharField(choices=[('MALE', 'مردانه'), ('FEMALE', 'زنانه'), ('UNISEX', 'مشترک')], max_length=6, verbose_name='جنسیت')),
                ('volume', models.CharField(choices=[('10m', '10m'), ('20m', '20m'), ('30m', '30m'), ('50m', '50m'), ('60m', '60m'), ('100m', '100m'), ('120m', '120m'), ('150m', '150m')], max_length=4, verbose_name='حجم')),
                ('perfume_type', models.CharField(choices=[('PERFUME', 'پرفیوم'), ('EAU_DE_PARFUM', 'ادوپرفیوم'), ('EAU_DE_TOILETTE', 'ادوتویلت'), ('EAU_DE_COLOGNE', 'ادوکلن'), ('BODY_SPLASH', 'بادی اسپلش')], max_length=15, verbose_name='نوع')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSmell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('گلفام', 'Golfam'), ('چوبی', 'Woody'), ('میوه ای', 'Fruity'), ('مرکباتی', 'Citrus'), ('دریایی', 'Marine'), ('شرقی', 'Oriental'), ('ادویه ای', 'Spicy'), ('فوژه', 'Fougere'), ('چرمی', 'Leathery'), ('مدیترانه ای', 'Mediterranean'), ('آروماتیک', 'Aromatic')], max_length=15, verbose_name='گروه بویایی')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم محصول')),
                ('name_en', models.CharField(help_text='به انگلیسی', max_length=100, verbose_name='اسم محصول')),
                ('pid', models.CharField(max_length=6, unique=True, verbose_name='کد محصول')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت محصول')),
                ('discount', models.IntegerField(default=-1, help_text='-۱ برای لغو تخفیف', validators=[django.core.validators.MinValueValidator(-1)], verbose_name='قیمت پس از تخفیف')),
                ('inventory', models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')),
                ('short_description', tinymce.models.HTMLField(verbose_name='توضیحات کوتاه')),
                ('description', tinymce.models.HTMLField(verbose_name='توضیحات اصلی')),
                ('video', models.FileField(blank=True, null=True, upload_to=shop.models.product_dynamic_path, verbose_name='ویدیو توضیحات')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدید ها')),
                ('is_visible', models.BooleanField(default=False, verbose_name='نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
                ('bought_by', models.ManyToManyField(blank=True, related_name='saved_products', to=settings.AUTH_USER_MODEL, verbose_name='کسانی که این محصول را خریده اند')),
                ('categories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category', verbose_name='دسته بندی ها')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_products', to=settings.AUTH_USER_MODEL, verbose_name='کسانی که این محصول را پسندیده اند')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shop.models.product_dynamic_path, verbose_name='تصویر')),
                ('alt', models.TextField(help_text='برای سئو', verbose_name='تیتر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='محصولات')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, verbose_name='ویزگی')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='shop.product', verbose_name='محصول')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='smell',
            field=models.ManyToManyField(blank=True, null=True, to='shop.productsmell', verbose_name='گروه بویایی'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='shop_produc_created_ddfb00_idx'),
        ),
    ]
