# Generated by Django 5.2 on 2025-05-02 16:04

import shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'ویژگی', 'verbose_name_plural': 'ویژگی ها'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AlterModelOptions(
            name='productsmell',
            options={'verbose_name': 'گروه بویایی', 'verbose_name_plural': 'گروه های بویایی'},
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('MALE', 'مردانه'), ('FEMALE', 'زنانه'), ('UNISEX', 'مشترک')], default=1, max_length=6, verbose_name='جنسیت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='last_view',
            field=models.DateTimeField(blank=True, null=True, verbose_name='اخرین بازدید'),
        ),
        migrations.AddField(
            model_name='product',
            name='nature',
            field=models.CharField(choices=[('WARM', 'گرم'), ('COLD', 'سرد')], default=1, max_length=4, verbose_name='طبع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='perfume_type',
            field=models.CharField(choices=[('PERFUME', 'پرفیوم'), ('EAU_DE_PARFUM', 'ادوپرفیوم'), ('EAU_DE_TOILETTE', 'ادوتویلت'), ('EAU_DE_COLOGNE', 'ادوکلن'), ('BODY_SPLASH', 'بادی اسپلش')], default=1, max_length=15, verbose_name='نوع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='remind_to',
            field=models.ManyToManyField(blank=True, related_name='reminder_products', to=settings.AUTH_USER_MODEL, verbose_name='کسانی که منتظر موجود شدن این محصول هستند'),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('WINTER', 'زمستانی'), ('SUMMER', 'تابستانی')], default=1, max_length=8, verbose_name='فصل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='smell',
            field=models.ManyToManyField(blank=True, null=True, to='shop.productsmell', verbose_name='گروه بویایی'),
        ),
        migrations.AddField(
            model_name='product',
            name='taste',
            field=models.CharField(choices=[('SPICY', 'تند'), ('SWEET', 'شیرین'), ('BITTER', 'تلخ'), ('SOUR', 'ترش')], default=1, max_length=6, verbose_name='طعم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(choices=[('10m', '10m'), ('20m', '20m'), ('30m', '30m'), ('50m', '50m'), ('60m', '60m'), ('100m', '100m'), ('120m', '120m'), ('150m', '150m')], default=1, max_length=4, verbose_name='حجم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(help_text='برای سئو', verbose_name='تیتر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='نمایش در سایت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='به فارسی', max_length=100, verbose_name='اسم محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, help_text='.mp4', null=True, upload_to=shop.models.product_dynamic_path, validators=[shop.models.video_validator], verbose_name='ویدیو توضیحات'),
        ),
        migrations.AlterField(
            model_name='productsmell',
            name='value',
            field=models.CharField(choices=[('GOLFAM', 'گلفام'), ('WOODY', 'چوبی'), ('FRUITY', 'میوه ای'), ('CITRUS', 'مرکباتی'), ('MARINE', 'دریایی'), ('ORIENTAL', 'شرقی'), ('SPICY', 'ادویه ای'), ('FOUGERE', 'فوژه'), ('LEATHERY', 'چرمی'), ('MEDITERRANEAN', 'مدیترانه ای'), ('AROMATIC', 'آروماتیک')], max_length=15, verbose_name='گروه بویایی'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
