# Generated by Django 5.2 on 2025-05-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categories',
        ),
        migrations.AlterModelOptions(
            name='productsmell',
            options={'verbose_name': 'گروه بویایی', 'verbose_name_plural': 'گروه های بویایی'},
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('MALE', 'مردانه'), ('FEMALE', 'زنانه'), ('UNISEX', 'مشترک')], default=1, max_length=6, verbose_name='جنسیت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='nature',
            field=models.CharField(choices=[('WARM', 'گرم'), ('COLD', 'سرد')], default=1, max_length=4, verbose_name='طبع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='perfume_type',
            field=models.CharField(choices=[('PERFUME', 'پرفیوم'), ('EAU_DE_PARFUM', 'ادوپرفیوم'), ('EAU_DE_TOILETTE', 'ادوتویلت'), ('EAU_DE_COLOGNE', 'ادوکلن'), ('BODY_SPLASH', 'بادی اسپلش')], default=1, max_length=15, verbose_name='نوع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('WINTER', 'زمستانی'), ('SUMMER', 'تابستانی')], default=1, max_length=8, verbose_name='فصل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='smell',
            field=models.ManyToManyField(blank=True, null=True, to='shop.productsmell', verbose_name='گروه بویایی'),
        ),
        migrations.AddField(
            model_name='product',
            name='taste',
            field=models.CharField(choices=[('SPICY', 'تند'), ('SWEET', 'شیرین'), ('BITTER', 'تلخ'), ('SOUR', 'ترش')], default=1, max_length=6, verbose_name='طعم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(choices=[('10m', '10m'), ('20m', '20m'), ('30m', '30m'), ('50m', '50m'), ('60m', '60m'), ('100m', '100m'), ('120m', '120m'), ('150m', '150m')], default=1, max_length=4, verbose_name='حجم'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='به فارسی', max_length=100, verbose_name='اسم محصول'),
        ),
        migrations.AlterField(
            model_name='productsmell',
            name='value',
            field=models.CharField(choices=[('GOLFAM', 'گلفام'), ('WOODY', 'چوبی'), ('FRUITY', 'میوه ای'), ('CITRUS', 'مرکباتی'), ('MARINE', 'دریایی'), ('ORIENTAL', 'شرقی'), ('SPICY', 'ادویه ای'), ('FOUGERE', 'فوژه'), ('LEATHERY', 'چرمی'), ('MEDITERRANEAN', 'مدیترانه ای'), ('AROMATIC', 'آروماتیک')], max_length=15, verbose_name='گروه بویایی'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
