# Generated by Django 5.2 on 2025-05-02 14:40

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_categories_alter_productsmell_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'ویژگی', 'verbose_name_plural': 'ویژگی ها'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AddField(
            model_name='product',
            name='last_view',
            field=models.DateTimeField(blank=True, null=True, verbose_name='اخرین بازدید'),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(help_text='برای سئو', verbose_name='تیتر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='نمایش در سایت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, help_text='.mp4', null=True, upload_to=shop.models.product_dynamic_path, validators=[shop.models.video_validator], verbose_name='ویدیو توضیحات'),
        ),
    ]
