# Generated by Django 5.2 on 2025-05-04 16:37

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_categories_alter_features_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='durability',
            field=models.CharField(choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('HIGH', 'زیاد')], default=1, max_length=6, verbose_name='ماندگاری'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='800*900', upload_to=shop.models.product_dynamic_path, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='به تومان', verbose_name='قیمت محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.CharField(choices=[('10m', '۱۰ میل'), ('20m', '۲۰ میل'), ('30m', '۳۰ میل'), ('50m', '۵۰ میل'), ('60m', '۶۰ میل'), ('100m', '۱۰۰ میل'), ('120m', '۱۲۰ میل'), ('150m', '۱۵۰ میل')], max_length=4, verbose_name='حجم'),
        ),
    ]
