# Generated by Django 5.2 on 2025-05-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_durability_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='به ازای هر میل / به تومان', verbose_name='قیمت محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.CharField(choices=[('10', '۱۰ میل'), ('20', '۲۰ میل'), ('30', '۳۰ میل'), ('50', '۵۰ میل'), ('60', '۶۰ میل'), ('100', '۱۰۰ میل'), ('120', '۱۲۰ میل'), ('150', '۱۵۰ میل')], max_length=4, verbose_name='حجم'),
        ),
    ]
