# Generated by Django 5.2 on 2025-05-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
    ]
