# Generated by Django 5.2 on 2025-05-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_comment_options_alter_comment_disliked_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='disliked_by',
        ),
    ]
