# Generated by Django 5.2 on 2025-05-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_comment_disliked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: ۱۰ میل', max_length=100, verbose_name='اسم')),
                ('volume', models.PositiveIntegerField(default=1, help_text='به میل', verbose_name='حجم')),
            ],
            options={
                'verbose_name': 'حجم',
                'verbose_name_plural': 'حجم ها',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='volume',
        ),
        migrations.AddField(
            model_name='product',
            name='available_volumes',
            field=models.ManyToManyField(blank=True, to='shop.volume', verbose_name='حجم های موجود'),
        ),
    ]
