# Generated by Django 5.2 on 2025-05-06 10:19

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_volume_remove_product_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='banner',
            field=models.ImageField(default=1, help_text='285*336', upload_to='Brands/Banner', verbose_name='بنر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(default=1, help_text='45*45 | white BG', upload_to='Brands/Logo', verbose_name='لوگو'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='800*900 | white BG', upload_to=shop.models.product_dynamic_path, verbose_name='تصویر'),
        ),
    ]
