# Generated by Django 5.2 on 2025-05-07 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_brand_banner_brand_logo_alter_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_volumes',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.volume', verbose_name='حجم های موجود'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.brand', verbose_name='برند'),
        ),
    ]
