# Generated by Django 5.2 on 2025-05-07 09:49

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_product_site_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام برند'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='No Background | .png or .webp', upload_to=shop.models.product_dynamic_path, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='name',
            field=models.CharField(help_text='مثال: ۱۰ میل', max_length=100, unique=True, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='volume',
            field=models.PositiveIntegerField(default=1, help_text='به میل', unique=True, verbose_name='حجم'),
        ),
    ]
