# Generated by Django 5.2 on 2025-05-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_brand_name_alter_brand_slug_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmell',
            name='value',
            field=models.CharField(choices=[('GOLFAM', 'گلفام'), ('WOODY', 'چوبی'), ('FRUITY', 'میوه ای'), ('CITRUS', 'مرکباتی'), ('MARINE', 'دریایی'), ('EASTERN', 'شرقی'), ('SPICY', 'ادویه ای'), ('FOUGERE', 'فوژه'), ('LEATHERY', 'چرمی'), ('MEDITERRANEAN', 'مدیترانه ای'), ('AROMATIC', 'آروماتیک')], max_length=15, verbose_name='گروه بویایی'),
        ),
    ]
