# Generated by Django 5.2 on 2025-05-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_productsmell_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spread',
            field=models.CharField(choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('HIGH', 'زیاد')], default='LOW', max_length=6, verbose_name='پخش بو'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='به ازای هر گرم / به تومان', verbose_name='قیمت محصول'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='name',
            field=models.CharField(help_text='مثال: ۱۰ گرم', max_length=100, unique=True, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='volume',
            field=models.PositiveIntegerField(default=1, help_text='به گرم', unique=True, verbose_name='حجم'),
        ),
    ]
