# Generated by Django 5.2 on 2025-05-14 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_spread_alter_product_price_alter_volume_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bought_by',
            field=models.ManyToManyField(blank=True, related_name='bought_products', to=settings.AUTH_USER_MODEL, verbose_name='کسانی که این محصول را خریده اند'),
        ),
    ]
