# Generated by Django 5.2 on 2025-05-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_product_bought_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='durability',
            field=models.CharField(choices=[('LOW', 'بالا'), ('MEDIUM', 'متوسط'), ('HIGH', 'پایین')], max_length=6, verbose_name='ماندگاری'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nature',
            field=models.CharField(choices=[('WARM', 'گرم'), ('COLD', 'خنک')], max_length=4, verbose_name='طبع'),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('WINTER', 'پاییز - زمستان'), ('SUMMER', 'بهار - تابستان')], max_length=8, verbose_name='فصل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spread',
            field=models.CharField(choices=[('LOW', 'ضعیف'), ('MEDIUM', 'متوسط'), ('HIGH', 'قوی')], max_length=6, verbose_name='پخش بو'),
        ),
    ]
