# Generated by Django 5.2 on 2025-05-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_product_durability_alter_product_nature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reset_discount_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان تخفیف'),
        ),
    ]
