# Generated by Django 5.2 on 2025-05-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_product_reset_discount_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsmell',
            name='value',
        ),
        migrations.AddField(
            model_name='productsmell',
            name='name',
            field=models.CharField(default='golfam', max_length=15, verbose_name='گروه بویایی'),
            preserve_default=False,
        ),
    ]
