# Generated by Django 5.2 on 2025-05-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_productsmell_value_productsmell_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmell',
            name='name',
            field=models.CharField(max_length=50, verbose_name='گروه بویایی'),
        ),
    ]
