# Generated by Django 5.2 on 2025-06-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_productsmell_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('WINTER', 'پاییز - زمستان'), ('SUMMER', 'بهار - تابستان'), ('ALL_SEASONS', 'چهار فصل')], max_length=12, verbose_name='فصل'),
        ),
    ]
