# Generated by Django 5.2 on 2025-06-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_product_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmell',
            name='icon',
            field=models.ImageField(default=1, help_text='80*80', upload_to='Smells/Icons', verbose_name='آیکون'),
            preserve_default=False,
        ),
    ]
