# Generated by Django 5.2 on 2025-05-09 07:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0016_alter_productsmell_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=12, unique=True, verbose_name='کد سفارش')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='ایمیل')),
                ('province', models.CharField(blank=True, max_length=30, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='شهر')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='کد پستی')),
                ('not_for_me', models.BooleanField(default=False, verbose_name='سفارش برای شخص دیگری است')),
                ('receive_type', models.CharField(choices=[('POST', 'به صورت پستی'), ('IN_PERSON', 'به صورت حضوری')], max_length=13, verbose_name='نوع دریافت')),
                ('receive_time', models.DateField(blank=True, null=True, verbose_name='زمان دریافت')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار تایید'), ('CONFIRMED', 'تایید شد'), ('IN_PROGRESS', 'در حال آماده سازی'), ('READY_TO_SHIP', 'آماده تحویل'), ('SHIPPED', 'تحویل داده شد'), ('FINISHED', 'تکمیل شد'), ('REJECTED', 'لغو شد')], max_length=17, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='توضیحات سفارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت سفارش')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10, verbose_name='کد تخقیف')),
                ('value', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='تخفیف به درصد')),
                ('selected', models.CharField(default='', help_text='products:<<slug1;slug2;...> or all>|p_exclude:<slug1;slug2;...>|users:<id1;id2;...> or all|u_exclude:<id1;id2;...>', verbose_name='محصولات و کاربران انتخاب شده')),
                ('expire_at', models.CharField(help_text='بر اساس لیست انقضا', verbose_name='انقضا')),
                ('users', models.ManyToManyField(related_name='used_discounts', to=settings.AUTH_USER_MODEL, verbose_name='کسانی که از این تخفیف استفاده کرده اند')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('price', models.PositiveIntegerField(default=0, help_text='با در نظر گرفتن حجم و تعداد', verbose_name='هزینه')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='محصول')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.volume', verbose_name='حجم')),
            ],
        ),
    ]
