# Generated by Django 5.2 on 2025-05-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'تخفیف', 'verbose_name_plural': 'تخفیف ها'},
        ),
        migrations.AlterField(
            model_name='discount',
            name='expire_at',
            field=models.DateField(verbose_name='زمان انقضا'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NOT_PAID', 'پرداخت نشده'), ('PENDING', 'در انتظار تایید'), ('CONFIRMED', 'تایید شد'), ('IN_PROGRESS', 'در حال آماده سازی'), ('READY_TO_SHIP', 'آماده تحویل'), ('SHIPPED', 'تحویل داده شد'), ('FINISHED', 'تکمیل شد'), ('REJECTED', 'لغو شد')], max_length=17, verbose_name='وضعیت'),
        ),
    ]
