# Generated by Django 5.2 on 2025-05-09 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_discount_options_alter_discount_expire_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='used_discounts', to=settings.AUTH_USER_MODEL, verbose_name='کسانی که از این تخفیف استفاده کرده اند'),
        ),
    ]
