# Generated by Django 5.2 on 2025-05-09 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_discount_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10, verbose_name='توکن کارت')),
                ('credit', models.PositiveIntegerField(verbose_name='اعتبار کارت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('created_by', models.ForeignKey(on_delete=models.SET('حذف شده'), to=settings.AUTH_USER_MODEL, verbose_name='خریداری شده توسط')),
            ],
            options={
                'verbose_name': 'کارت اعتباری',
                'verbose_name_plural': 'کارت های اعتباری',
            },
        ),
    ]
