# Generated by Django 5.2 on 2025-05-09 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_creditcart_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('GATEWAY', 'از طریق درگاه پرداخت'), ('CREDIT', 'با کارت اعتباری')], max_length=21, verbose_name='نوع پرداخت')),
                ('paid_amount', models.IntegerField(verbose_name='هزینه دریافتی')),
                ('content', models.TextField(verbose_name='توضیحات')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order', verbose_name='برای سفارش')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='توسط')),
            ],
        ),
    ]
