# Generated by Django 5.2 on 2025-05-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش ها'},
        ),
    ]
