# Generated by Django 5.2 on 2025-05-13 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_transaction_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receive_type',
            field=models.CharField(choices=[('POST', 'به صورت پستی'), ('IN_PERSON', 'به صورت حضوری')], default='POST', max_length=13, verbose_name='نوع دریافت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NOT_PAID', 'پرداخت نشده'), ('PENDING', 'در انتظار تایید'), ('CONFIRMED', 'تایید شد'), ('IN_PROGRESS', 'در حال آماده سازی'), ('READY_TO_SHIP', 'آماده تحویل'), ('SHIPPED', 'تحویل داده شد'), ('FINISHED', 'تکمیل شد'), ('REJECTED', 'لغو شد')], default='NOT_PAID', max_length=17, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='order.order', verbose_name='برای سفارش'),
        ),
    ]
