# Generated by Django 5.2 on 2025-05-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_user_alter_order_receive_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='content',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
    ]
