# Generated by Django 5.2 on 2025-06-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_orderitem_volume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcart',
            options={'verbose_name': 'کارت هدیه', 'verbose_name_plural': 'کارت های هدیه'},
        ),
        migrations.AddField(
            model_name='order',
            name='national_code',
            field=models.CharField(default=1, max_length=10, verbose_name='کد ملی'),
            preserve_default=False,
        ),
    ]
