'''
Django settings for Neyanbar project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
'''
from pathlib import Path
from django.contrib import admin
from melipayamak import Api
import os.path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment variables
ENV = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ENV('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = ENV.bool('DEBUG', default=True)

ALLOWED_HOSTS = ENV.list('ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main.apps.MainConfig',
    'account.apps.AccountConfig',
    'blog.apps.BlogConfig',
    'shop.apps.ShopConfig',
    'cart.apps.CartConfig',
    'order.apps.OrderConfig',
    'tinymce',
    'django_social_share',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'main.middlewares.SiteAccessMiddleware',
]

ROOT_URLCONF = 'Neyanbar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
                'main.context_processors.base'
            ],
        },
    },
]

WSGI_APPLICATION = 'Neyanbar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': ENV('DB_NAME'),
        'USER': ENV('DB_USER'),
        'PASSWORD': ENV('DB_PASSWORD'),
    }
}

# Cache backend

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIR = [
    BASE_DIR / 'static',
]
# Media files (Blog, Products, ...)

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Jazzmin settings

JAZZMIN_SETTINGS = {
    'custom_css': 'css/jazzmin-rtl.css',
    'site_brand': 'داشبورد',
}
admin.sites.AdminSite.site_header = 'پنل مدیریت'
admin.sites.AdminSite.site_title = 'فروشگاه'
admin.sites.AdminSite.index_title = 'پنل مدیریت'

# Tinymce settings

TINYMCE_DEFAULT_CONFIG = {
    'height': 500,
    'width': '100%',
    'menubar': True,
    'plugins': (
        'advlist anchor autolink autosave charmap code codesample directionality emoticons fullscreen help '
        'image insertdatetime link lists media nonbreaking pagebreak paste preview print quickbars save searchreplace '
        'table template visualblocks visualchars wordcount'
    ),
    'toolbar': (
        'undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | '
        'alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist | forecolor backcolor '
        'removeformat | pagebreak | charmap emoticons | fullscreen preview save print | '
        'insertfile image media template link anchor codesample | ltr rtl | code'
    ),
    'contextmenu': 'link image imagetools table',
    'images_upload_url': '/blog/editor/upload/',
    'automatic_uploads': True,
    'image_advtab': True,
    'image_caption': True,
    'file_picker_types': 'file image media',
    'quickbars_selection_toolbar': 'bold italic | quicklink h2 h3 blockquote quickimage quicktable',
    'nonbreaking_force_tab': True,
    'toolbar_mode': 'sliding',
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# User model

AUTH_USER_MODEL = 'account.User'

# Zarinpal

MERCHANT = ENV('MERCHANT')

SANDBOX = ENV.bool('SANDBOX', default=False)

CALLBACK_URL = ENV('CALLBACK_URL')

# Melypayamak

SMS_USERNAME = ENV('SMS_USERNAME')
SMS_PASSWORD = ENV('SMS_PASSWORD')
SMS = Api(SMS_USERNAME, SMS_PASSWORD).sms()

# Postex

POSTEX_CONFIG = {
    'api_key': ENV('POSTEX_API_KEY'),
    'payment_method': 'SENDER',  # SENDER - RECEIVER - COD
    'courier': {  # Pishtaz
        'courier_code': 'IR_POST',
        'service_type': 'EXPRESS'
    },
    'postal_code': ENV('POSTAL_CODE'),
    'city_id': ENV('CITY_ID'),
    'city_name': ENV('CITY_NAME'),
    'address': ENV('ADDRESS'),
    'sms_notification': True,
    'email_notification': True,
    'request_pickup': False,
    'request_delivery': False,
    'ready_to_accept': False,
}
